# Generated by Django 4.1.7 on 2023-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=13)),
                ('room_no', models.CharField(max_length=13)),
                ('cap', models.CharField(max_length=20)),
                ('rent_room', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=130)),
            ],
        ),
    ]
