# Generated by Django 4.1.7 on 2023-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGApp', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_room_name', models.CharField(max_length=13)),
                ('booked_room_no', models.CharField(max_length=13)),
                ('booked_cap', models.CharField(max_length=20)),
                ('booked_rent_room', models.CharField(max_length=13)),
                ('booked_description', models.CharField(max_length=130)),
            ],
        ),
    ]
