# Generated by Django 4.1.7 on 2023-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGApp', '0003_bookingrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrooms',
            name='booked_user',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
