# Generated by Django 4.1.7 on 2023-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGApp', '0004_bookingrooms_booked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrooms',
            name='booked_user',
            field=models.CharField(max_length=30),
        ),
    ]
